-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
CREATE TABLE public.companies (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    brand_name text,
    website text,
    additional_information text,
    target_audience text,
    brand_tone text,
    key_offer text,
    CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ideas (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    header text,
    platforms text,
    description text,
    angle_number integer,
    angle_id bigint,
    topic1 text,
    idea_description1 text,
    image_prompt1 text,
    topic2 text,
    idea_description2 text,
    image_prompt2 text,
    topic3 text,
    idea_description3 text,
    image_prompt3 text,
    topic4 text,
    idea_description4 text,
    image_prompt4 text,
    topic5 text,
    idea_description5 text,
    image_prompt5 text,
    topic6 text,
    idea_description6 text,
    image_prompt6 text,
    topic7 text,
    idea_description7 text,
    image_prompt7 text,
    topic8 text,
    idea_description8 text,
    image_prompt8 text,
    topic9 text,
    idea_description9 text,
    image_prompt9 text,
    topic10 text,
    idea_description10 text,
    image_prompt10 text,
    strategy_id bigint NOT NULL,
    company_id bigint NOT NULL,
    CONSTRAINT ideas_pkey PRIMARY KEY (id),
    CONSTRAINT ideas_strategy_id_fkey FOREIGN KEY (strategy_id) REFERENCES public.strategies(id),
    CONSTRAINT ideas_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.linkedin_content (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    company_id bigint NOT NULL,
    strategy_id bigint,
    idea_id bigint NOT NULL,
    CONSTRAINT linkedin_content_pkey PRIMARY KEY (id),
    CONSTRAINT linkedin_content_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
    CONSTRAINT linkedin_content_strategy_id_fkey FOREIGN KEY (strategy_id) REFERENCES public.strategies(id),
    CONSTRAINT linkedin_content_idea_id_fkey FOREIGN KEY (idea_id) REFERENCES public.ideas(id)
);
CREATE TABLE public.newsletter_content (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    company_id bigint NOT NULL,
    strategy_id bigint,
    idea_id bigint NOT NULL,
    CONSTRAINT newsletter_content_pkey PRIMARY KEY (id),
    CONSTRAINT newsletter_content_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
    CONSTRAINT newsletter_content_strategy_id_fkey FOREIGN KEY (strategy_id) REFERENCES public.strategies(id),
    CONSTRAINT newsletter_content_idea_id_fkey FOREIGN KEY (idea_id) REFERENCES public.ideas(id)
);
CREATE TABLE public.real_estate_content (
    id bigint,
    created_at timestamp with time zone,
    link_origin text,
    link_final text
);
CREATE TABLE public.strategies (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    platforms text,
    angle1_header text,
    angle1_description text,
    angle1_objective text,
    angle1_tonality text,
    angle2_header text,
    angle2_description text,
    angle2_objective text,
    angle2_tonality text,
    angle3_header text,
    angle3_description text,
    angle3_objective text,
    angle3_tonality text,
    angle4_header text,
    angle4_description text,
    angle4_objective text,
    angle4_tonality text,
    angle5_header text,
    angle5_description text,
    angle5_objective text,
    angle5_tonality text,
    angle6_header text,
    angle6_description text,
    angle6_objective text,
    angle6_tonality text,
    angle7_header text,
    angle7_description text,
    angle7_objective text,
    angle7_tonality text,
    angle8_header text,
    angle8_description text,
    angle8_objective text,
    angle8_tonality text,
    angle9_header text,
    angle9_description text,
    angle9_objective text,
    angle9_tonality text,
    angle10_header text,
    angle10_description text,
    angle10_objective text,
    angle10_tonality text,
    company_id bigint NOT NULL,
    CONSTRAINT strategies_pkey PRIMARY KEY (id),
    CONSTRAINT strategies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.twitter_content (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    company_id bigint NOT NULL,
    strategy_id bigint,
    idea_id bigint NOT NULL,
    content_body text,
    CONSTRAINT twitter_content_pkey PRIMARY KEY (id),
    CONSTRAINT twitter_content_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
    CONSTRAINT twitter_content_strategy_id_fkey FOREIGN KEY (strategy_id) REFERENCES public.strategies(id),
    CONSTRAINT twitter_content_idea_id_fkey FOREIGN KEY (idea_id) REFERENCES public.ideas(id)
);
